// <auto-generated />
using System;
using Education.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Education.Persistence.Migrations
{
    [DbContext(typeof(EducationDbContext))]
    partial class EducationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Education.Domain.Curso", b =>
                {
                    b.Property<Guid>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = new Guid("02e4ffd8-5e78-40ad-b3e9-87051fad3589"),
                            Descripcion = "Curso de c# basico",
                            FechaCreacion = new DateTime(2022, 4, 21, 10, 36, 59, 737, DateTimeKind.Local).AddTicks(8519),
                            FechaPublicacion = new DateTime(2024, 4, 21, 10, 36, 59, 737, DateTimeKind.Local).AddTicks(8554),
                            Precio = 56m,
                            Titulo = "C# desde cero hasta avanzado"
                        },
                        new
                        {
                            CursoId = new Guid("cb71db42-7372-41a7-8b3a-6258175686a2"),
                            Descripcion = "Curso de Java",
                            FechaCreacion = new DateTime(2022, 4, 21, 10, 36, 59, 737, DateTimeKind.Local).AddTicks(8577),
                            FechaPublicacion = new DateTime(2024, 4, 21, 10, 36, 59, 737, DateTimeKind.Local).AddTicks(8579),
                            Precio = 25m,
                            Titulo = "Master en Java Spring desde las raices"
                        },
                        new
                        {
                            CursoId = new Guid("f9098ddc-df6f-46de-94fe-726bf7464821"),
                            Descripcion = "Curso de Unit Test para NET Core",
                            FechaCreacion = new DateTime(2022, 4, 21, 10, 36, 59, 737, DateTimeKind.Local).AddTicks(8587),
                            FechaPublicacion = new DateTime(2024, 4, 21, 10, 36, 59, 737, DateTimeKind.Local).AddTicks(8589),
                            Precio = 25m,
                            Titulo = "Master en UNIT Test con CQRS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
